<?php

$modversion['name'] = _XF_XFSNIPPET_NAME;

$modversion['version'] = 1.1;

$modversion['description'] = _XF_XFSNIPPET_DESC;

$modversion['author'] = 'Arjen van Efferen <br> Ported to Xoops V2 by Predator <br> Expand and Modified by Predator <br> http://www.myxoopsforge.de';

$modversion['credits'] = 'The XOOPS Project';

$modversion['help'] = '';

$modversion['license'] = 'GPL';

$modversion['official'] = 0;

$modversion['image'] = 'xfsnippet.png';

$modversion['dirname'] = 'xfsnippet';

$modversion['templates'][1]['file'] = 'xfsnippet_index.html';

$modversion['templates'][1]['description'] = '';

$modversion['templates'][2]['file'] = 'xfsnippet_detail.html';

$modversion['templates'][2]['description'] = '';

$modversion['templates'][3]['file'] = 'xfsnippet_browse.html';

$modversion['templates'][3]['description'] = '';

$modversion['templates'][4]['file'] = 'xfsnippet_addsnippet.html';

$modversion['templates'][4]['description'] = '';

$modversion['templates'][5]['file'] = 'xfsnippet_package.html';

$modversion['templates'][5]['description'] = '';

$modversion['templates'][6]['file'] = 'xfsnippet_ratesnippet.html';

$modversion['templates'][6]['description'] = '';

$modversion['templates'][7]['file'] = 'xfsnippet_submit.html';

$modversion['templates'][7]['description'] = '';

$modversion['templates'][8]['file'] = 'xfsnippet_addsnippettopackage.html';

$modversion['templates'][8]['description'] = '';

$modversion['templates'][9]['file'] = 'xfsnippet_addpackage.html';

$modversion['templates'][9]['description'] = '';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)

// All tables should not have any prefix!

$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)

$modversion['tables'][0] = 'xf_snippet';

$modversion['tables'][1] = 'xf_snippet_category';

$modversion['tables'][2] = 'xf_snippet_language';

$modversion['tables'][3] = 'xf_snippet_package';

$modversion['tables'][4] = 'xf_snippet_package_item';

$modversion['tables'][5] = 'xf_snippet_package_version';

$modversion['tables'][6] = 'xf_snippet_type';

$modversion['tables'][7] = 'xf_snippet_version';

$modversion['tables'][8] = 'xf_snippet_votedata';

// Admin things

$modversion['hasAdmin'] = 1;

$modversion['adminindex'] = 'admin/index.php';

$modversion['adminmenu'] = 'admin/menu.php';

// Menu

$modversion['hasMain'] = 1;

$modversion['hasComments'] = 1;

$modversion['comments']['itemName'] = 'snippet_id';

$modversion['comments']['pageName'] = 'detail.php';

// Comment callback functions

$modversion['comments']['callbackFile'] = 'include/comment_functions.php';

$modversion['comments']['callback']['approve'] = 'xfsnippet_com_approve';

$modversion['comments']['callback']['update'] = 'xfsnippet_com_update';

// Search

$modversion['hasSearch'] = 1;

$modversion['search']['file'] = 'include/search.inc.php';

$modversion['search']['func'] = 'snippet_search';
